apiVersion: v1
kind: Pod
metadata:
  name: react-front
  labels:
    app: react-front
spec:
  containers:
    - image: aurelius0523/react-front
      name: react-front
      ports:
        - containerPort: 80
