spring:
  profiles:
    active: facade-mock, service-mock, repository-mock
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:spring
    username: sa
    password: